/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_safenetinc_Common */

#ifndef _Included_com_safenetinc_Common
#define _Included_com_safenetinc_Common
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_safenetinc_Common
 * Method:    MofnAuthentication
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_com_safenetinc_Common_MofnAuthentication
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_safenetinc_Common
 * Method:    GetPass
 * Signature: ()[C
 */
JNIEXPORT jcharArray JNICALL Java_com_safenetinc_Common_GetPass
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
